name: Scheduled Netlify Deploy

on:
  schedule:
    - cron: '0 10,16,23 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Deploy
        run: curl -X POST ${{ secrets.NETLIFY_DEPLOY_HOOK }}
